import { DirectusEvent, DirectusTestimonial, DirectusDownload } from './directus.interfaces';

export const MOCK_EVENTS: DirectusEvent[] = [
  {
    id: '1a2b3c4d-0001-4000-8000-000000000001',
    status: 'published',
    slug: 'pumptrack-worlds-2024',
    title: 'Pumptrack World Championships 2024',
    subtitle: 'The biggest pumptrack event on the planet',
    date: '2024-09-14',
    location: 'Bern, Switzerland',
    flag_emoji: '🇨🇭',
    description: '<p>The 2024 Pumptrack World Championships brought together over 200 riders from 30+ countries to compete on a stunning track in Bern, Switzerland.</p><p>Symax provided full <strong>timing, scoring, and broadcast graphics</strong> — powered by Phoenix. Every split, every finish, delivered in real-time to screens worldwide.</p>',
    cover_image: null,
    gallery: [],
    tags: ['Pumptrack', 'UCI', 'World Championships', 'Broadcast'],
    featured: true,
    show_scoreboard: true,
    phoenix_event_id: 'pumptrack-wc-2024',
    phoenix_api_url: null,
    sort: 1,
  },
  {
    id: '1a2b3c4d-0002-4000-8000-000000000002',
    status: 'published',
    slug: 'austria-qualifier-2026',
    title: 'Austria Qualifier 2026',
    subtitle: 'AREA 47 — First Phoenix 2.0 Deployment',
    date: '2026-03-21',
    location: 'AREA 47, Austria',
    flag_emoji: '🇦🇹',
    description: '<p>The first live deployment of <strong>Phoenix 2.0</strong> — the new cloud-native timing platform. AREA 47 in Austria served as the proving ground for the next generation of race timing.</p><p>New architecture, same precision. The future of race timing starts here.</p>',
    cover_image: null,
    gallery: [],
    tags: ['Pumptrack', 'Phoenix 2.0', 'Cloud', 'Qualifier'],
    featured: true,
    show_scoreboard: false,
    phoenix_event_id: null,
    phoenix_api_url: null,
    sort: 2,
  },
  {
    id: '1a2b3c4d-0003-4000-8000-000000000003',
    status: 'published',
    slug: 'yogyakarta-international-2024',
    title: 'Yogyakarta International',
    subtitle: '2,300 Riders — Road Cycling',
    date: '2024-06-15',
    location: 'Yogyakarta, Indonesia',
    flag_emoji: '🇮🇩',
    description: '<p>A massive road cycling event in Indonesia with over <strong>2,300 registered riders</strong>. Phoenix handled every single entry with real-time results throughout the event.</p><p>Proving that the platform scales from 50 to 2,300+ riders without breaking a sweat.</p>',
    cover_image: null,
    gallery: [],
    tags: ['Road', 'International', 'Scale'],
    featured: false,
    show_scoreboard: true,
    phoenix_event_id: 'yogyakarta-2024',
    phoenix_api_url: null,
    sort: 3,
  },
  {
    id: '1a2b3c4d-0004-4000-8000-000000000004',
    status: 'published',
    slug: 'uci-mtb-worlds-2024',
    title: 'UCI MTB World Championships 2024',
    subtitle: 'Contracted by Swisstiming',
    date: '2024-08-28',
    location: 'Val di Sole, Switzerland',
    flag_emoji: '🇨🇭',
    description: '<p>Swisstiming contracted Symax to deliver <strong>broadcast-quality live graphics</strong> at the UCI Mountain Bike World Championships.</p><p>Professional graphics pipeline integrated with Phoenix timing data — delivered to the world broadcast feed in real-time.</p>',
    cover_image: null,
    gallery: [],
    tags: ['MTB', 'UCI', 'Swisstiming', 'Broadcast'],
    featured: false,
    show_scoreboard: false,
    phoenix_event_id: null,
    phoenix_api_url: null,
    sort: 4,
  },
];

export const MOCK_TESTIMONIALS: DirectusTestimonial[] = [
  {
    id: 'test-0001',
    status: 'published',
    quote: 'Phoenix transformed how we deliver race results. The real-time data and broadcast graphics are a step above anything we\'ve used before.',
    author_name: 'Race Timing Director',
    author_role: 'Professional Timing Provider',
    author_initials: 'TD',
    sort: 1,
  },
  {
    id: 'test-0002',
    status: 'published',
    quote: 'The graphics quality rivals what you see on WorldTour broadcasts. Our audience and sponsors were blown away by the production value.',
    author_name: 'Event Organizer',
    author_role: 'International Cycling Event',
    author_initials: 'EO',
    sort: 2,
  },
  {
    id: 'test-0003',
    status: 'published',
    quote: 'Finally, a platform that works with our existing hardware. Zero switching costs, immediate upgrade in results quality.',
    author_name: 'Timing Professional',
    author_role: 'UCI Event Contractor',
    author_initials: 'TP',
    sort: 3,
  },
];

export const MOCK_DOWNLOAD: DirectusDownload = {
  id: 'dl-0001',
  status: 'published',
  version: 'v2.0',
  release_date: '2026-03-01',
  release_notes: 'First cloud release. Multi-tenant architecture, RaceHub integration, real-time SSE event stream.',
  windows_file: null,
  macos_file: null,
  linux_file: null,
  sort: 1,
};

export const MOCK_SCOREBOARD = [
  { pos: 1, name: 'T. Hrastnik', time: '00:41.832', gap: '—' },
  { pos: 2, name: 'M. Vossen', time: '00:42.107', gap: '+0.275' },
  { pos: 3, name: 'R. Daudet', time: '00:42.388', gap: '+0.556' },
  { pos: 4, name: 'A. Walker', time: '00:42.901', gap: '+1.069' },
  { pos: 5, name: 'P. Ropero', time: '00:43.214', gap: '+1.382' },
  { pos: 6, name: 'J. Nyhaug', time: '00:43.548', gap: '+1.716' },
  { pos: 7, name: 'S. Marquart', time: '00:43.821', gap: '+1.989' },
  { pos: 8, name: 'K. Fields', time: '00:44.002', gap: '+2.170' },
];
